# Generated by Django 6.0.1 on 2026-05-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_is_online_meeting_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
    ]
