# Generated by Django 6.0.1 on 2026-01-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_dailyqr_delete_checkinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
