# Generated by Django 6.0.1 on 2026-01-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='qr_used',
        ),
    ]
