# Generated by Django 6.0.1 on 2026-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_dailyqr_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
