# Generated by Django 6.0.1 on 2026-01-16 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('CP', 'Congés Payés'), ('RTT', 'RTT'), ('SICK', 'Maladie'), ('TRAINING', 'Formation'), ('UNPAID', 'Sans solde'), ('MATERNITY', 'Maternité'), ('PATERNITY', 'Paternité')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
