# Generated by Django 6.0.1 on 2026-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, upload_to='leave_attachments/'),
        ),
    ]
