# Generated by Django 6.0.1 on 2026-01-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_qr_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyqr',
            name='purpose',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], default='CHECK_IN', max_length=15),
            preserve_default=False,
        ),
    ]
